### ISSUE TITLE
[Bug]: Could not make ore furnaces with 4 stone and 1 coal.

### ISSUE THREAD

**Issue by Vyndakator** [Vanderlin-Tales-Of-Wine/Vanderlin#171]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

I was trying to build an ore furnace and forge with a dwarven longbeard. Had average crafting, and 4 stone, 1 coal. I could not make it.

### How to reproduce

Tried to make a furnace with the appropriate items. Even tried it with wood in the pile, nothing.

### Round ID

Cant recall

### Staff ckey

Cant recall

**Comment by dwasint** [comment]
was this through the craft button? Most structures use a slap crafting system now
